-- Clavis · GENERATED by matugen · do not edit
-- Source: matugen/templates/nvim-colors.lua
-- 语法映射：关键字=accent 粗体 · 类型=amber · 函数=info · 字符串=success ·
--   注释=faint 斜体 · 数字/常量=accent2 · 诊断 error=danger / warn=warning。
-- 明暗不再读 ~/.config/theme/active：matugen 按当前 scheme 直接渲染，
-- 由 surface 的相对亮度判定 vim.o.background。

local M = {}

local c = {
  pane     = "{{ colors.surface.default.hex }}",
  surface2 = "{{ colors.surface_container_high.default.hex }}",
  line     = "{{ colors.outline_variant.default.hex }}",
  sel      = "{{ colors.secondary_container.default.hex }}",
  ink      = "{{ colors.on_surface.default.hex }}",
  muted    = "{{ colors.on_surface_variant.default.hex }}",
  faint    = "{{ colors.outline.default.hex }}",
  accent   = "{{ colors.glass_accent.default.hex }}",
  accent2  = "{{ colors.glass_accent2.default.hex }}",
  danger   = "{{ colors.glass_danger.default.hex }}",
  info     = "{{ colors.glass_info.default.hex }}",
  warning  = "{{ colors.glass_warning.default.hex }}",
  success  = "{{ colors.glass_success.default.hex }}",
  cyan     = "{{ colors.glass_cyan.default.hex }}",
  amber    = "{{ colors.glass_amber.default.hex }}",
}

-- 由背景色的相对亮度决定 background，避免依赖外部模式标记文件
local function is_dark(hex)
  local r, g, b = hex:match("^#(%x%x)(%x%x)(%x%x)$")
  if not r then return true end
  local lum = 0.2126 * tonumber(r, 16) + 0.7152 * tonumber(g, 16) + 0.0722 * tonumber(b, 16)
  return lum < 128
end

local function hl(groups)
  for g, v in pairs(groups) do vim.api.nvim_set_hl(0, g, v) end
end

function M.load()
  vim.o.background = is_dark(c.pane) and "dark" or "light"
  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
  vim.g.colors_name = "matugen"

  hl({
    -- 编辑区不设 bg：留给终端的半透明底，否则玻璃被实底挡掉
    Normal        = { fg = c.ink },
    NormalNC      = { fg = c.ink },
    NormalFloat   = { fg = c.ink, bg = c.surface2 },
    FloatBorder   = { fg = c.line },
    FloatTitle    = { fg = c.accent, bold = true },
    Comment       = { fg = c.faint, italic = true },
    Constant      = { fg = c.accent2 },
    String        = { fg = c.success },
    Character     = { fg = c.success },
    Number        = { fg = c.accent2 },
    Boolean       = { fg = c.accent2 },
    Identifier    = { fg = c.ink },
    Function      = { fg = c.info },
    Statement     = { fg = c.accent, bold = true },
    Keyword       = { fg = c.accent, bold = true },
    Operator      = { fg = c.muted },
    Type          = { fg = c.amber },
    Special       = { fg = c.cyan },
    PreProc       = { fg = c.cyan },
    Underlined    = { fg = c.info, underline = true },
    Todo          = { fg = c.pane, bg = c.warning, bold = true },
    Error         = { fg = c.danger, bold = true },

    LineNr        = { fg = c.faint },
    CursorLineNr  = { fg = c.accent, bold = true },
    CursorLine    = { bg = c.surface2 },
    CursorColumn  = { bg = c.surface2 },
    ColorColumn   = { bg = c.surface2 },
    Visual        = { bg = c.sel },
    Search        = { fg = c.pane, bg = c.warning },
    IncSearch     = { fg = c.pane, bg = c.accent },
    MatchParen    = { fg = c.accent, bold = true },
    SignColumn    = { fg = c.faint },
    VertSplit     = { fg = c.line },
    WinSeparator  = { fg = c.line },
    Folded        = { fg = c.muted, bg = c.surface2 },
    Pmenu         = { fg = c.ink, bg = c.surface2 },
    PmenuSel      = { fg = c.accent, bg = c.sel, bold = true },
    PmenuSbar     = { bg = c.surface2 },
    PmenuThumb    = { bg = c.muted },
    StatusLine    = { fg = c.ink, bg = c.surface2 },
    StatusLineNC  = { fg = c.muted, bg = c.surface2 },
    TabLine       = { fg = c.muted, bg = c.surface2 },
    TabLineSel    = { fg = c.accent, bg = c.pane, bold = true },
    TabLineFill   = { bg = c.pane },
    Title         = { fg = c.accent, bold = true },
    Directory     = { fg = c.info },
    Question      = { fg = c.success },
    MoreMsg       = { fg = c.success },
    WarningMsg    = { fg = c.warning },
    ErrorMsg      = { fg = c.danger },
    NonText       = { fg = c.faint },
    Whitespace    = { fg = c.faint },
    SpecialKey    = { fg = c.faint },

    DiagnosticError = { fg = c.danger },
    DiagnosticWarn  = { fg = c.warning },
    DiagnosticInfo  = { fg = c.info },
    DiagnosticHint  = { fg = c.muted },
    DiagnosticOk    = { fg = c.success },

    DiffAdd       = { fg = c.success },
    DiffChange    = { fg = c.warning },
    DiffDelete    = { fg = c.danger },
    DiffText      = { fg = c.accent, bold = true },

    ["@variable"]       = { fg = c.ink },
    ["@property"]       = { fg = c.cyan },
    ["@field"]          = { fg = c.cyan },
    ["@parameter"]      = { fg = c.ink },
    ["@type"]           = { fg = c.amber },
    ["@function"]       = { fg = c.info },
    ["@function.call"]  = { fg = c.info },
    ["@keyword"]        = { fg = c.accent, bold = true },
    ["@string"]         = { fg = c.success },
    ["@number"]         = { fg = c.accent2 },
    ["@comment"]        = { fg = c.faint, italic = true },
    ["@punctuation"]    = { fg = c.muted },
    ["@constant"]       = { fg = c.accent2 },
    ["@tag"]            = { fg = c.accent },
  })
end

-- matugen 重写本文件后，回到 nvim 时自动重载（渲染进程不通知 nvim）
vim.api.nvim_create_autocmd({ "FocusGained", "VimResume" }, {
  callback = function() M.load() end,
})

M.load()
return M
